server:
  port: 8080

spring:
  application:
    name: task-service


  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: task_user
    password: task_user

  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  kafka:
    topics:
      task-created: task.created
      task-assigned: task.assigned

management:
  endpoints:
    web:
      exposure:
        include: health,info

